#-*-Python-*-
Import('env')
aw = env.Copy()
aw.Append(CPPPATH=['/usr/X11R6/include'])
aw.Append(LIBPATH=['/usr/X11R6/lib'])
aw.Append(LIBS=['X11', 'GL'])
aw.SharedLibrary('aw', ['aw.c', 'awx.c'])
aw.Install('include/aw', ['aw.h', 'sysgl.h', 'sysglu.h'])
awtest = env.Copy()
awtest.Append(CPPPATH=['include', '/usr/X11R6/include'])
awtest.Append(LIBS=['aw', 'GL', 'GLU', 'X11'])
awtest.Append(LIBPATH=['.', '/usr/X11R6/lib'])
awtest.Program('awtest', 'test/awtest.c')
awtest.Program('hello', 'test/hello.c')
awtest.Program('robot', 'test/robot.c')
awtest.Program('picksquare', 'test/picksquare.c')
awtest.Program('cube', 'test/cube.c')
